stages:
  - build
  - deploy
  - notification

variables:
  IMAGE_URL: "registry-sao.adata.com/$CI_PROJECT_PATH"
  BASE_SERVICE_NAME: "tmdb_backend"


.build_template: &build_definition
  stage: build
  tags:
    - saopaulo
  script:
    - docker build -t $IMAGE_URL:$CI_COMMIT_BRANCH -f .adata/Dockerfile .
    - docker push $IMAGE_URL:$CI_COMMIT_BRANCH
  allow_failure: false


build dev:
  <<: *build_definition
  only: [dev]

build test:
  <<: *build_definition
  only: [test]

build prod:
  <<: *build_definition
  only: [prod]

# 2. Deploy Script Dinâmico
deploy:
  stage: deploy
  script:
    - |
      if [ "$CI_COMMIT_BRANCH" == "prod" ]; then
        SERVER=$SERVER_SAO_PROD
        SERVICE_NAME="$BASE_SERVICE_NAME"
      else
        SERVER=$SERVER_SAO_TST
        SERVICE_NAME="$CI_COMMIT_BRANCH-$BASE_SERVICE_NAME"
      fi
      FULL_IMAGE_TAG="$IMAGE_URL:$CI_COMMIT_BRANCH"
      SSH_CMD="ssh -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_ed25519 -p $(echo $SSH_PORT | sed 's/[^0-9]*//g') $USER_SAO@$SERVER"

      echo "Iniciando deploy no ambiente $CI_COMMIT_BRANCH (Serviço: $SERVICE_NAME)"

      PULLED_IMAGE=$(eval "$SSH_CMD \"docker pull $FULL_IMAGE_TAG\"")
      UPDATE_IMAGE=$(eval "$SSH_CMD \"docker service update --detach=false --with-registry-auth --force --image $FULL_IMAGE_TAG $SERVICE_NAME\"")

      eval "$SSH_CMD \"~/app/scripts/ds-updater-sucess.sh \\\"$PULLED_IMAGE\\\" \\\"$UPDATE_IMAGE\\\"\""
  only:
    - dev
    - test
    - prod

deploy falha:
  stage: deploy
  script:
    - |
      if [ "$CI_COMMIT_BRANCH" == "prod" ]; then
        SERVER=$SERVER_SAO_PROD
        SERVICE_NAME="$BASE_SERVICE_NAME"
      else
        SERVER=$SERVER_SAO_TST
        SERVICE_NAME="$CI_COMMIT_BRANCH-$BASE_SERVICE_NAME"
      fi
      FULL_IMAGE_TAG="$IMAGE_URL:$CI_COMMIT_BRANCH"
      SSH_CMD="ssh -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_ed25519 -p $(echo $SSH_PORT | sed 's/[^0-9]*//g') $USER_SAO@$SERVER"

      MSG_FAILURE=$(echo $FULL_IMAGE_TAG $SERVICE_NAME)
      eval "$SSH_CMD \"~/app/scripts/ds-updater-failure.sh $MSG_FAILURE\""
  when: on_failure
  only:
    - dev
    - test
    - prod


notificação sucesso email:
  stage: notification
  script:
    - PROJECT_NAME=$(echo $CI_PROJECT_NAMESPACE | cut -d'/' -f2)
    - domain="$(echo $PROJECT_NAME-$CI_COMMIT_BRANCH | sed 's/-main$//')"
    - sendmail "$GITLAB_USER_LOGIN" "$GITLAB_USER_EMAIL" "[passed] $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME@$CI_COMMIT_BRANCH" "Olá $GITLAB_USER_LOGIN, seu deploy foi realizado com sucesso, seu ambiente ficará disponível em alguns instantes, o ambiente está em https://$domain.adata.com/api"
  when: on_success
  only:
    - prod
    - test
    - dev

notificação falha email:
  stage: notification
  script:
    - sendmail "$GITLAB_USER_LOGIN" "$GITLAB_USER_EMAIL" "[failed] $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME@$CI_COMMIT_BRANCH" "Olá $GITLAB_USER_LOGIN, não foi possível realizar o seu deploy. Verifique o log da pipeline para mais informações, qualquer problema entre em contato com luiz.vieira@adata.com"
  when: on_failure
  only:
    - prod
    - test
    - dev
